# Generated by Django 3.1.1 on 2020-10-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='createdate',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='completedate',
            new_name='datecompleted',
        ),
    ]
